"""Schemas for M-Pesa Business to Pochi B2Pochi API requests and responses.

B2Pochi is a variant of B2C used to pay a customer's business wallet
(Pochi La Biashara / Micro SME).
"""

from enum import Enum
from typing import List, Optional, Union

from pydantic import BaseModel, ConfigDict, Field, model_validator

from mpesakit.utils.phone import normalize_phone_number


class B2PCommandIDType(str, Enum):
    """Allowed values for CommandID in B2Pochi payment requests."""

    BusinessPayToPochi = "BusinessPayToPochi"


class B2PRequest(BaseModel):
    """Request schema for B2Pochi payment initiation.

    This schema is used to initiate Business-to-Pochi (B2Pochi) payments via
    the Safaricom Daraja API.

    NOTE: To use this API in production, you must apply for a Bulk
    Disbursement Account (or convert an existing Paybill/Till to a one
    account that can receive and disburse). The receiving party must have a
    Pochi La Biashara (Micro SME) wallet.

    https://developer.safaricom.co.ke/APIs/BusinessToPochi

    Attributes:
        OriginatorConversationID (str): Unique identifier generated by the
            merchant for every request, used to avoid double disbursement.
        InitiatorName (str): Username of the API user created on the M-PESA portal.
        SecurityCredential (str): Encrypted password of the API user.
        CommandID (str): Type of transaction. Must be BusinessPayToPochi.
        Amount (int): Transaction amount.
        PartyA (int): B2C organization shortcode sending the funds.
        PartyB (int): Customer mobile number receiving the money (12-digit MSISDN).
        Remarks (str): Additional information (2–100 characters).
        QueueTimeOutURL (str): URL for timeout notifications.
        ResultURL (str): URL for result notifications.
        Occassion (Optional[str]): Additional information (1–100 characters).
            Spelling matches the Daraja API field name.
    """

    OriginatorConversationID: str = Field(
        ..., description="Unique identifier for the specific request."
    )
    InitiatorName: str = Field(
        ..., description="Username used to initiate the request."
    )
    SecurityCredential: str = Field(..., description="Encrypted security credential.")
    CommandID: str = Field(
        default=B2PCommandIDType.BusinessPayToPochi.value,
        description="Type of transaction to perform.",
    )
    Amount: int = Field(..., description="Amount to be sent to the customer wallet.")
    PartyA: int = Field(..., description="Shortcode sending the funds.")
    PartyB: int = Field(..., description="Mobile number receiving the funds.")
    Remarks: str = Field(..., description="Comments for the transaction (2–100 chars).")
    QueueTimeOutURL: str = Field(..., description="URL for timeout notifications.")
    ResultURL: str = Field(..., description="URL for result notifications.")
    Occassion: Optional[str] = Field(
        None,
        description="Optional occasion for payment (Daraja field spelling).",
    )

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "OriginatorConversationID": "600997_Test_32et3241ed8yu",
                "InitiatorName": "testapi",
                "SecurityCredential": "encrypted_credential",
                "CommandID": "BusinessPayToPochi",
                "Amount": 10,
                "PartyA": 600992,
                "PartyB": 254705912645,
                "Remarks": "remarked",
                "QueueTimeOutURL": "https://example.com/timeout",
                "ResultURL": "https://example.com/result",
                "Occassion": "ChristmasPay",
            }
        }
    )

    @model_validator(mode="before")
    @classmethod
    def validate(cls, values):
        """Validate CommandID, PartyB, Remarks, and Occassion."""
        if not isinstance(values, dict):
            return values
        cls._validate_command_id(values)
        cls._validate_partyb(values)
        cls._validate_remarks(values)
        cls._validate_occassion(values)
        return values

    @classmethod
    def _validate_occassion(cls, values):
        """Ensure Occassion is between 1 and 100 characters when provided."""
        occasion = values.get("Occassion")
        if occasion is None:
            return values
        if len(occasion) == 0:
            values["Occassion"] = None
            return values
        if len(occasion) > 100:
            raise ValueError("Occassion must not exceed 100 characters.")
        return values

    @classmethod
    def _validate_remarks(cls, values):
        """Ensure Remarks is between 2 and 100 characters."""
        remarks = values.get("Remarks")
        if remarks is None:
            raise ValueError(
                "Remarks is required and must be between 2 and 100 characters."
            )
        if len(remarks) < 2 or len(remarks) > 100:
            raise ValueError("Remarks must be between 2 and 100 characters.")
        return values

    @classmethod
    def _validate_partyb(cls, values):
        """Ensure PartyB is a valid Kenyan phone number."""
        partyb = values.get("PartyB")
        normalized = normalize_phone_number(str(partyb))
        if normalized is None:
            raise ValueError(
                f"PartyB must be a valid Kenyan phone number, got '{partyb}'"
            )
        values["PartyB"] = int(normalized)
        return values

    @classmethod
    def _validate_command_id(cls, values):
        """Ensure CommandID is a valid B2PCommandIDType value."""
        command_id = values.get("CommandID")
        if command_id is None:
            values["CommandID"] = B2PCommandIDType.BusinessPayToPochi.value
            return values
        if isinstance(command_id, B2PCommandIDType):
            values["CommandID"] = command_id.value
            return values
        valid_ids = [e.value for e in B2PCommandIDType]
        if command_id not in valid_ids:
            raise ValueError(
                f"CommandID must be one of {valid_ids}, got '{command_id}'"
            )
        return values


class B2PResponse(BaseModel):
    """Immediate acknowledgement schema for a B2Pochi payment request."""

    ConversationID: Optional[str] = Field(
        ..., description="Unique ID for the payment request."
    )
    OriginatorConversationID: Optional[str] = Field(
        ..., description="ID for tracking the request."
    )
    ResponseCode: str | int = Field(..., description="Status code, 0 means success.")
    ResponseDescription: str = Field(..., description="Status message.")

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "ConversationID": "AG_20240706_20106e9209f64bebd05b",
                "OriginatorConversationID": "600997_Test_32et3241ed8yu",
                "ResponseCode": "0",
                "ResponseDescription": "Accept the service request successfully.",
            }
        }
    )

    @property
    def is_successful(self) -> bool:
        """Return True if ResponseCode indicates success (e.g., '0', '00000000')."""
        code = str(self.ResponseCode)
        return code.strip("0") == "" and code != ""


class B2PResultParameter(BaseModel):
    """Parameter item in B2Pochi result notification."""

    Key: str = Field(..., description="Parameter name.")
    Value: str | int | float = Field(..., description="Parameter value.")


class B2PReferenceItem(BaseModel):
    """Reference item in B2Pochi result notification."""

    Key: str = Field(..., description="Reference parameter name.")
    Value: Optional[str | int | float] = Field(
        None, description="Reference parameter value."
    )


class B2PResultParameters(BaseModel):
    """Container for result parameters in a B2Pochi callback."""

    ResultParameter: Union[List[B2PResultParameter], B2PResultParameter] = Field(
        ..., description="List of result parameters or a single parameter."
    )


class B2PReferenceData(BaseModel):
    """Container for reference data in a B2Pochi callback."""

    ReferenceItem: Union[List[B2PReferenceItem], B2PReferenceItem] = Field(
        ..., description="List of reference items or a single item."
    )


class B2PResultMetadata(BaseModel):
    """Metadata for B2Pochi result notification."""

    ResultType: int = Field(..., description="Type of result (usually 0).")
    ResultCode: int | str = Field(..., description="Result code (0=Success).")
    ResultDesc: str = Field(..., description="Result description.")
    OriginatorConversationID: str = Field(
        ..., description="Originator conversation ID."
    )
    ConversationID: str = Field(..., description="Conversation ID.")
    TransactionID: Optional[str] = Field(
        None, description="M-Pesa transaction ID (if available)."
    )
    ResultParameters: Optional[B2PResultParameters] = Field(
        None, description="Result parameters container."
    )
    ReferenceData: Optional[B2PReferenceData] = Field(
        None, description="Reference data."
    )

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "ResultType": 0,
                "ResultCode": 0,
                "ResultDesc": "The service request is processed successfully.",
                "OriginatorConversationID": "53e3-4aa8-9fe0-8fb5e4092cdd3533373",
                "ConversationID": "AG_20240706_2010364430d9bbdaf872",
                "TransactionID": "SG632NMUAB",
                "ResultParameters": {
                    "ResultParameter": [
                        {"Key": "TransactionAmount", "Value": 10},
                        {"Key": "TransactionReceipt", "Value": "SG632NMUAB"},
                    ]
                },
            }
        }
    )

    @model_validator(mode="before")
    @classmethod
    def normalize_nested_payload(cls, values):
        """Accept a flat ResultParameters list in addition to the nested Daraja shape."""
        if not isinstance(values, dict):
            return values
        result_parameters = values.get("ResultParameters")
        if isinstance(result_parameters, list):
            values["ResultParameters"] = {"ResultParameter": result_parameters}
        return values

    def _parameters_dict(self) -> dict:
        """Return result parameters as a key/value mapping."""
        if self.ResultParameters is None:
            return {}
        params = self.ResultParameters.ResultParameter
        if isinstance(params, list):
            return {param.Key: param.Value for param in params}
        return {params.Key: params.Value}

    @property
    def transaction_amount(self) -> Optional[int | float]:
        """Return the TransactionAmount value if present."""
        return self._parameters_dict().get("TransactionAmount")

    @property
    def transaction_receipt(self) -> Optional[str]:
        """Return the TransactionReceipt value if present."""
        return self._parameters_dict().get("TransactionReceipt")

    @property
    def recipient_is_registered(self) -> Optional[bool]:
        """Return True if B2CRecipientIsRegisteredCustomer is 'Y', False if 'N'."""
        val = self._parameters_dict().get("B2CRecipientIsRegisteredCustomer")
        if val == "Y":
            return True
        if val == "N":
            return False
        return None

    @property
    def receiver_party_public_name(self) -> Optional[str]:
        """Return the ReceiverPartyPublicName value if present."""
        return self._parameters_dict().get("ReceiverPartyPublicName")

    @property
    def transaction_completed_datetime(self) -> Optional[str]:
        """Return the TransactionCompletedDateTime value if present."""
        return self._parameters_dict().get("TransactionCompletedDateTime")

    @property
    def charges_paid_account_available_funds(self) -> Optional[float]:
        """Return the B2CChargesPaidAccountAvailableFunds value if present."""
        return self._parameters_dict().get("B2CChargesPaidAccountAvailableFunds")

    @property
    def utility_account_available_funds(self) -> Optional[float]:
        """Return the B2CUtilityAccountAvailableFunds value if present."""
        return self._parameters_dict().get("B2CUtilityAccountAvailableFunds")

    @property
    def working_account_available_funds(self) -> Optional[float]:
        """Return the B2CWorkingAccountAvailableFunds value if present."""
        return self._parameters_dict().get("B2CWorkingAccountAvailableFunds")


class B2PResultCallback(BaseModel):
    """Schema for B2Pochi result notification sent to ResultURL."""

    Result: B2PResultMetadata = Field(..., description="Result metadata.")

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "Result": {
                    "ResultType": 0,
                    "ResultCode": 0,
                    "ResultDesc": "The service request is processed successfully.",
                    "OriginatorConversationID": "53e3-4aa8-9fe0-8fb5e4092cdd3533373",
                    "ConversationID": "AG_20240706_2010364430d9bbdaf872",
                    "TransactionID": "SG632NMUAB",
                    "ResultParameters": {
                        "ResultParameter": [
                            {"Key": "TransactionAmount", "Value": 10},
                            {"Key": "TransactionReceipt", "Value": "SG632NMUAB"},
                        ]
                    },
                }
            }
        }
    )

    @property
    def is_successful(self) -> bool:
        """Return True if ResultCode indicates success (e.g., '0', '00000000')."""
        code = str(self.Result.ResultCode)
        return code.strip("0") == "" and code != ""


class B2PResultCallbackResponse(BaseModel):
    """Schema for response to B2Pochi result callback."""

    ResultCode: int | str = Field(
        default=0, description="Result code (0=Success, other=Failure)."
    )
    ResultDesc: str = Field(
        default="Result received and processed successfully.",
        description="Result description.",
    )

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "ResultCode": 0,
                "ResultDesc": "Result received and processed successfully.",
            }
        }
    )


class B2PTimeoutCallback(BaseModel):
    """Schema for B2Pochi timeout notification sent to QueueTimeOutURL."""

    Result: B2PResultMetadata = Field(..., description="Result metadata.")

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "Result": {
                    "ResultType": 1,
                    "ResultCode": "1",
                    "ResultDesc": "The service request timed out.",
                    "OriginatorConversationID": "53e3-4aa8-9fe0-8fb5e4092cdd3544366",
                    "ConversationID": "AG_20240707_201062f6f6f5804f7a33",
                }
            }
        }
    )


class B2PTimeoutCallbackResponse(BaseModel):
    """Schema for response to B2Pochi timeout callback."""

    ResultCode: int | str = Field(
        default=0,
        description="Result code (0=Success, other=Failure).",
    )
    ResultDesc: str = Field(
        default="Timeout notification received and processed successfully.",
        description="Result description.",
    )

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "ResultCode": 0,
                "ResultDesc": "Timeout notification received and processed successfully.",
            }
        }
    )
